# Generated by Django 4.1.7 on 2023-02-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arana', '0003_alter_product_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='registered',
            field=models.BooleanField(default=True),
        ),
    ]
